name: 'Buf generate'
description: 'Uses Buf to generate compiled protos'
inputs:
  working-directory:
    description: Working directory
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Install Buf
      uses: bufbuild/buf-setup-action@v0.6.0
      with:
        version: '1.0.0-rc12'
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'
        cache: 'pip'
    - name: Setup cache
      uses: actions/cache@v2
      with:
        # In order:
        # * go Module download cache
        # * go Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.github-token }}
    - name: Install go dependencies
      shell: bash
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - name: Install npm dependencies
      shell: bash
      run: |
        npm install grpc-tools grpc_tools_node_protoc_ts --global
    - name: Install python dependencies # We use betterproto https://github.com/danielgtaylor/python-betterproto to generate python grpc code, so we have to install it
      shell: bash
      run: |
        pip install "betterproto[compiler]"
        pip install betterproto
    - name: Run buf generate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        buf generate